name: Build and Test with Gradle

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Use Java 11 for Gradle

    - name: Set up Gradle
      uses: gradle/wrapper-validation-action@v1
      with:
        gradle-wrapper-file: gradle/wrapper/gradle-wrapper.properties  # Optional: specify wrapper file path

    - name: Build with Gradle
      run: ./gradlew build  # Run Gradle build command

    - name: Run tests with Gradle
      run: ./gradlew test  # Run tests with Gradle
